# $Id: Makefile 87305 2016-02-08 13:50:32Z lafferty $
# ===============================================================================
# Purpose: simple Makefile by Patrick Koppenburg on 2015-06-26
# ===============================================================================

TARGET = diagram.pdf
LATEX = pdflatex

all: $(TARGET)

%.pdf : %.tex
	pdflatex $<

